version: "3.8"
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=<YourStrong@Passw0rd>
    ports:
      - "1433:1433"
  backend:
    image: animal-shelter-backend_1.1
    container_name: backend
    ports:
      - "5000:80"
    build:
      context: ./RestApi
      dockerfile: RestApi/Dockerfile
    depends_on:
       - sqlserver
  frontend:
    image: animal-shelter-frontend_1.1
    container_name: frontend
    ports:
      - "4200:80"
    links:
      - backend
    build:
      context: ./Frontend/AnimalShelter
      dockerfile: Dockerfile
